apiVersion: v2
dependencies:
- name: common
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
  version: 1.x.x
- name: alfresco-common
  repository: https://kubernetes-charts.alfresco.com/incubator
  version: 0.1.0-SNAPSHOT
description: Alfresco Sync Service
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- syncservice
- alfresco
- application
name: alfresco-sync-service
sources:
- https://github.com/Alfresco/acs-deployment
version: 3.0.9
