apiVersion: v2
dependencies:
- name: alfresco-common
  repository: https://kubernetes-charts.alfresco.com/stable
  version: 0.1.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
  version: 10.16.2
- alias: postgresql-syncservice
  condition: alfresco-sync-service.syncservice.enabled,postgresql-syncservice.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/
  version: 10.16.2
- alias: alfresco-digital-workspace
  condition: alfresco-content-services.alfresco-digital-workspace.enabled,alfresco-digital-workspace.enabled
  name: common
  repository: https://activiti.github.io/activiti-cloud-helm-charts
  version: 7.3.0
- condition: activemq.enabled
  name: activemq
  repository: ""
  version: 2.1.0
- condition: alfresco-search.enabled
  name: alfresco-search
  repository: ""
  version: 1.0.4
- condition: alfresco-elasticsearch-connector.enabled
  name: alfresco-elasticsearch-connector
  repository: ""
  version: 0.1.0
- name: alfresco-sync-service
  repository: ""
  version: 3.0.9
- alias: elasticsearch
  condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.10.1
description: A Helm chart for deploying Alfresco Content Services
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- content
- content services
- alfresco
- alfresco content services
name: alfresco-content-services
sources:
- https://github.com/Alfresco/acs-deployment
version: 5.3.0
