apiVersion: v2
appVersion: 5.16.4
dependencies:
- name: alfresco-common
  repository: https://kubernetes-charts.alfresco.com/incubator
  version: 0.1.0-SNAPSHOT
description: A Helm chart Providing Apache ActiveMQ.
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- activemq
- message broker
name: activemq
sources:
- https://github.com/Alfresco/acs-deployment
version: 2.1.0
